listen=YES
listen_ipv6=NO

anonymous_enable=NO
local_enable=YES
write_enable=YES

chroot_local_user=YES
allow_writeable_chroot=YES
local_root=/var/www/html

pasv_enable=YES
pasv_min_port=21000
pasv_max_port=21010

seccomp_sandbox=NO
xferlog_enable=YES
